### ISSUE TITLE
Log Issue

### ISSUE THREAD

**Issue by th3fallen** [FormidableLabs/webpack-dashboard#149]
> Please provide a description of the bug / issue, and provide the details below:

Log displaying full webpack output vs shortened version i'd expect that is shown in docs?

====================================================================

###### If the issue is visual, please provide screenshots here
http://th3fallen.d.pr/mtaC

====================================================================

###### Steps to reproduce the problem
run npm start with the below config

====================================================================

###### Please provide a gist of relevant files

1. package.json ```"start": "export NODE_ENV=dev && webpack-dashboard -- node -r babel-register server.js",```
2. webpack.config.js
```const webpack = require('webpack');
const path = require('path');
const DashboardPlugin = require('webpack-dashboard/plugin');

const cwd = process.cwd();

module.exports = {
  devtool: 'eval-source-map',
  entry: {
    dev: [
      'webpack-dev-server/client?http://localhost:3000',
      'webpack/hot/only-dev-server',
    ],
  },
  output: {
    filename: 'assets/js/[name].js',
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new DashboardPlugin(),
  ],```
3. index.js (Your express based dev server, if applicable)
```const webpack = require('webpack');
const WebpackDevServer = require('webpack-dev-server');
const config = require('./webpack.config');

const compiler = webpack(config);

new WebpackDevServer(compiler, {
  publicPath: config.output.publicPath,
  quiet: true,
  hot: true,
  historyApiFallback: true,
}).listen(3000, 'localhost', (err, result) => {
  if (err) {
    return console.log(err);
  }

  console.log('Listening at http://localhost:3000/');
});
```

====================================================================

###### More Details

- What operating system are you on? OSX
- What terminal application are you using? iTerm
- What version of webpack-dashboard are you using? 0.3.0
- What is the output of running `echo $TERM`? xterm-256color

**Comment by jamez14** [comment]
Also seeing this. Using webpack-dashboard v0.3.0 and webpack v2.2.1. When using any version earlier than 0.3.0 (i.e. v0.2.0) it was working as expected.

It appears the webpack-dev-server `--quiet` flag is not being respected.

I am running webpack-dev-server & webpack-dashboard via this command:
`webpack-dashboard -c blue -- webpack-dev-server -d --quiet --inline --https --config ./webpack.dev.js`

![screen shot 2017-02-09 at 12 52 05 pm](https://cloud.githubusercontent.com/assets/2854919/22796018/d0571c8c-eec6-11e6-90cc-63737af447c6.png)

**Comment by dkrutsko** [comment]
Can confirm. Downgrading to webpack-dashboard `~0.2` solved this problem.

**Comment by nlutterman** [comment]
I was just taking a poke at it.  It appears that `webpack-dashboard` just grabs the resulting stats object that's provided by `webpack` itself during the `done` event for plugins.  The most recent change was to allow `webpack-dashboard` to gather data directly from the socket rather than from stdio.

The downside, apparently, to this is that the output is verbose, as it's not filtered by webpack beforehand.  (That's my ignorant guess at the moment.)  It's just slurping it right out of it as it's compiled.  We'll have to figure out how webpack applies its own filters and utilize them through its API. Maybe?

**Comment by nlutterman** [comment]
Alright, I did some digging.  These are the two changes I propose to fix the issue:

```javascript
    plugin/index.js:104    value: stats.toString()
```

to

```javascript
    plugin/index.js:104    value: stats.toString(stats.compilation.options.stats)
```

is the change that respects what the user has set to be for the output from webpack.

_or_

We could send the `stats` object to the handler for the log, so that the handler can decide how to format it changing (`plugin/index.js:102-105`):

```javascript
        }. {
          type: "log",
          value: stats.toString()
        }]);
```

to

```javascript
        }. {
          type: "log",
          stats: stats
          value: stats.toString()
        }]);
```

That would let the user change the value to whatever they wanted.

Example:

```javascript
webpack.config.js

const dashboard = new Dashboard();

{
    ...
    plugins: [
        ... ,
        new DashboardPlugin(
            function dashboardHandler(data) {
                let log = data.find((elem) => elem.type === "log")
                if (log) {
                    log.value = stats.toString(stats.compilation.options.stats)
                }
                return dashboard.setData(data);
            }
    ],
    ...
}
```
_Or_ there could be an option that the user could specify to use webpack's stats` options.  Like the first recommendation, but conditional.

So, hope that helps you guys!  If you want it to just work without being verbose, then do the first thing I recommended after updating it.

**Comment by th3fallen** [comment]
@kenwheeler could you tag that commit so we can consume it?

**Comment by binarykitchen** [comment]
hmm, read all the above but still do not see the official solution how to reduce the log output?
