### ISSUE TITLE
Too many Node instances crashes my mac!

### ISSUE THREAD

**Issue by human-a** [FormidableLabs/webpack-dashboard#179]
Hi

I tried the webpack dashboard and also [the desktop app](https://github.com/FormidableLabs/electron-webpack-dashboard) for it and I really loved it but it crashes my Mac because it runs out of RAM after an hour or so.

###### Steps to reproduce the problem

Just adding the ```new DashboardPlugin()``` line to my webpack config is enough to crash my iMac (late 2015) with 24GBs of RAM after about 1 hour of running my dev server. I don't even need to run the desktop app for the dashboard, just including the plugin line into my webpack dev config is enough to crash the Mac. I am using react-create-app boilerplate configurations for webpack.

```javascript
"webpack": "^1.13.3"
"webpack-dev-server": "^1.16.1"
```

**Comment by jwbrew** [comment]
I've experienced exactly the same. Will try and find a more accurate cause/PR a fix if possible - really useful tool & would love to contribute. 

webpack 2.2.1
webpack-dev-server 1.16.2

**Comment by smrq** [comment]
Same behavior here.  Every rebuild causes a new instance of Node to spawn.  In my case I'm using Storybook with a customized Webpack config to add the dashboard plugin.

```
webpack@2.7.0
webpack-dev-server@2.7.1
```

**Comment by smrq** [comment]
After some investigation, I believe what is happening is that new instances of `InspectpackDaemon` are being spawned on every compile and never terminated.  This seems to have been fixed by https://github.com/FormidableLabs/webpack-dashboard/commit/58c355c053b000dcb6715ffbab49354634ec03fd, so I suspect that others having this issue should make sure to update to `webpack-dashboard@1.0.0-5` and this issue can likely be closed.

`webpack-dashboard@next` still points to `1.0.0-4`, which is how I ended up with an outdated version, so that should probably be updated to the fixed revision.

**Comment by ryan-roemer** [comment]
@human-a -- Can you upgrade to `^1.0.1` and try again? We've updated how inspectpack spawns...

If the issue persists, can you create a minimal repository with install + reproduction steps so that we can jump in and more quickly figure out what's going on?

**Comment by ryan-roemer** [comment]
`inspectpack` has been rewritten from scratch to (1) use the webpack stats object only, (2) not do any minification or gzipping, which means we don't spawn any workers or have any binary deps anymore. Consequently, the `webpack-dashboard@^2` plugin should now be as fast as any arbitrary webpack plugin that parses the stats object.
