### ISSUE TITLE
[Bug] Webpack empty manifest file produces "Error: No code sections found" exception.

### ISSUE THREAD

**Issue by Batbold-Gansukh** [FormidableLabs/webpack-dashboard#189]
`No code sections found` is thrown when used with `CommonsChunkPlugin`.

====================================================================

![screen shot 2017-09-03 at 09 35 01](https://user-images.githubusercontent.com/480945/29999894-9dba4c08-9093-11e7-9987-a401c686fb12.png)

====================================================================

Demo:
https://github.com/Batbold-Gansukh/dashboard-demo
npm install
npm start

====================================================================

###### More Details

OSX 10.12.6
ITerm2
1.0.0-5
xterm-256color

**Comment by ryan-roemer** [comment]
@Batbold-Gansukh -- Can you provide your webpack configuration and if this is an OSS project, link to the repo and reproduction steps? If a closed source project, I'll review your webpack config first, then ask for further steps.

@kenwheeler -- Can we get a template for filing issues that requires a webpack config and sample bundle for reproduction? (With closed source code removed).

**Comment by Batbold-Gansukh** [comment]
I did provide simple reproducible demo.
https://github.com/Batbold-Gansukh/dashboard-demo Is this not working for you?

webpack config file
https://github.com/Batbold-Gansukh/dashboard-demo/blob/master/webpack.js
```
const WebpackMd5Hash = require ( 'webpack-md5-hash' );
const webpack = require('webpack');
const Express         = require ( 'express' )
const DashboardPlugin = require ( 'webpack-dashboard/plugin' )

const webpackConfig = {
  entry:Object.assign({},{
    a:['webpack-hot-middleware/client?path=/__webpack_hmr&reload=true','./a.js'],
    b:['webpack-hot-middleware/client?path=/__webpack_hmr&reload=true','./b.js'],
  }),
  resolve:{
    extensions:['.js']
  },
    
  output:{
    path:"/",
    filename:"[name].js",
  },

  devtool:'inline-source-map',
  plugins:[
    new WebpackMd5Hash(),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoEmitOnErrorsPlugin(),
    /* Removing CommonsChunkPlugin resolves the issue */
    new webpack.optimize.CommonsChunkPlugin({
      names:['manifest'],
      filename:"[name].js",
      minChunks:Infinity,
    }),
  ]
}

const webpackCompiler = webpack(webpackConfig);
webpackCompiler.apply(new DashboardPlugin());

const serverOptions = {
  contentBase:"http://localhost:8080",
  quiet:false,
  noInfo:false,
  hot:true,
  inline:true,
  watchOptions:{
    aggregateTime:300,
    poll:false,
    ignored:/node_modules/
  },
  lazy:false,
  stats:{colors:true}
}

const app = new Express();
app.use(require('webpack-dev-middleware')(webpackCompiler,serverOptions));
app.use(require('webpack-hot-middleware')(webpackCompiler))

app.listen(8080,function listenining(err){
  if(err){
    console.error(err);
  }else{
    console.info('webpack read');
  }
})
```

**Comment by ryan-roemer** [comment]
@Batbold-Gansukh -- Oh jeez, total reading comprehension fail on my part. Yeah, that's perfect. I'll jump into your demo repo on Tuesday and see what we can come up with. Thanks!

**Comment by ryan-roemer** [comment]
I've pulled the repo and found the issue. For my experiment, I just outputted to a build directory and looked at the files.

## Side Note

As a preliminary comment, make sure to enable:

```js
  output:{
    pathinfo: true
  },
```

to get full path names for all JS code chunks when using `inspectpack` or the dashboard projects.

### Experiment

I changed the webpack config to dump to file with:

```diff
diff --git a/.gitignore b/.gitignore
index 3c3629e..b7dab5e 100644
--- a/.gitignore
+++ b/.gitignore
@@ -1 +1,2 @@
 node_modules
+build
\ No newline at end of file
diff --git a/webpack.js b/webpack.js
index 5e13291..ab7217c 100644
--- a/webpack.js
+++ b/webpack.js
@@ -1,5 +1,6 @@
 const WebpackMd5Hash = require ( 'webpack-md5-hash' );
 const webpack = require('webpack');
+const path = require('path');
 const Express         = require ( 'express' )
 const DashboardPlugin = require ( 'webpack-dashboard/plugin' )
 
@@ -11,10 +12,11 @@ const webpackConfig = {
   resolve:{
     extensions:['.js']
   },
-    
+
   output:{
-    path:"/",
+    path: path.resolve("build"),
     filename:"[name].js",
+    pathinfo: true
   },
 
   devtool:'inline-source-map',
@@ -31,32 +33,4 @@ const webpackConfig = {
   ]
 }
 
-const webpackCompiler = webpack(webpackConfig);
-webpackCompiler.apply(new DashboardPlugin());
-
-const serverOptions = {
-  contentBase:"http://localhost:8080",
-  quiet:false,
-  noInfo:false,
-  hot:true,
-  inline:true,
-  watchOptions:{
-    aggregateTime:300,
-    poll:false,
-    ignored:/node_modules/
-  },
-  lazy:false,
-  stats:{colors:true}
-}
-
-const app = new Express();
-app.use(require('webpack-dev-middleware')(webpackCompiler,serverOptions));
-app.use(require('webpack-hot-middleware')(webpackCompiler))
-
-app.listen(8080,function listenining(err){
-  if(err){
-    console.error(err);
-  }else{
-    console.info('webpack read');
-  }
-})
+module.exports = webpackConfig;
```

(Note that I _did_ add the `pathinfo: true`). Our files:

```sh
$ webpack --config webpack.js 

$ ls build | cat
a.js
b.js
manifest.js
```

So, `a`, `b`, and `manifest`. When running raw `inspectpack` commands, here's what I get:

```sh
$ inspectpack -a sizes -b build/a.js 
inspectpack --action=sizes
==========================

## Summary

* Bundle:
    * Path:                    build/a.js
    * Bytes (min):             57394
    * Bytes (min+gz):          18524

## Files                  
. ./node_modules/html-entities/lib/html5-entities.js
  * Type:          code
  * Size:          49027
  * Size (min):    41757
  * Size (min+gz): 12207

# ... OTHER INSPECTPACK OUTPUT SNIPPED ...
```

```sh
$ inspectpack -a sizes -b build/b.js 
inspectpack --action=sizes
==========================

## Summary

* Bundle:
    * Path:                    build/b.js
    * Bytes (min):             57396
    * Bytes (min+gz):          18525

## Files                  
. ./node_modules/html-entities/lib/html5-entities.js
  * Type:          code
  * Size:          49027
  * Size (min):    41757
  * Size (min+gz): 12207

# ... OTHER INSPECTPACK OUTPUT SNIPPED ...
```

But, when we get to `manifest.js` we get:

```sh
$ inspectpack -a sizes -b build/manifest.js 
Error: No code sections found
    at Bundle.validate (/Users/rye/scm/vendor/Batbold-Gansukh-dashboard-demo/node_modules/inspectpack/lib/models/bundle.js:45:11)
    at fs.readFile (/Users/rye/scm/vendor/Batbold-Gansukh-dashboard-demo/node_modules/inspectpack/lib/models/bundle.js:296:14)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:504:3)
```

So, let's look at that file:

```js
/******/ (function(modules) { // webpackBootstrap
/******/ 	// SNIPPED -- whole buncha webpack boilerplate
/******/ })
/************************************************************************/
/******/ ([]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,
SNIPPED_WHOLE_BUNCHA_ENCODED_SOURCE_MAP
```

Notice that `([])`? With the `CommonCodeChunks` plugin set to `minChunks:Infinity,` you have no overlapping code sections, and thus `inspectpack` rightly complains "No Code Sections found" (because there aren't any).

Reading up, it looks like you're using [this strategy](https://webpack.js.org/plugins/commons-chunk-plugin/#manifest-file) to only put the webpack loading boilerplate and no actual code in a shared file to avoid that overhead in your separate a and b entry points.

So for @kenwheeler and @tptee -- if I'm understanding things correctly, we have a use case where -one_ of the files that we're analyzing specifically _wants_ to have no code sections. Some thoughts:

1. Maybe we special case this in the webpack-dashboard layer? Also note that `[ACTION]` api calls now accept a `{ allowEmpty: true }` option that may be useful.
2. We enhance `inspectpack` to detect `([])` that there in fact **are** no code sections, and just allow empty from there, because the error is meant really to say that "there are code sections but I can't infer them". Maybe a simple babel parse?
