### ISSUE TITLE
multiple node progress in Activity Monitor

### ISSUE THREAD

**Issue by lukastong** [FormidableLabs/webpack-dashboard#227]
using `webpack-dashboard/plugin` in my front end project.
there will be shown multiple node progresses in Acitivity Monitor, and the fe project squash frequency is pretty high...
when i uninstall this plugin. everything will be ok.

**Comment by FourwingsY** [comment]
Yes webpack-dashboard devours the CPU usage. when i was using `webpack-dashboard@^0.4.0`, it was better.

**Comment by ocha** [comment]
I had exactly same problem. Made it impossible to work on laptop with battery. I found out it was caused by `inspectpack` that was added in v1.0. I disabled it by adding `--minimal` command to my webpack-dashboard command and all issues are gone. CPU usage is 0% again. 👍

**Comment by ocha** [comment]
it would be great if readme gave information about this change and possible solutions/choices. I went down wrong rabbit hole trying to figure out what was eating up my CPU and ended up losing lots of time.

Since this is making working on laptop impossible, I think it should be an opt-in feature or at least clearly outline in readme that starting v1.0 there is a huge CPU usage because of inspectpack, and one can use --minimal flag to disable it.

**Comment by ryan-roemer** [comment]
CPU usage is only huge if you have a lot of bundle size (aka it's a factor of if your prod bundles take a long time). We semver majored to `1.0` with the `inspectpack` addition -- which also brought new features like minified individual sizes, etc.

@kenwheeler -- I think we can either document it since folks are surprised that minification causes a CPU hit (along with `--minimal` to remove all inspectpack stuff) and/or do opt-out flags. Maybe do the opt-out flags so folks can decide if it's just the minification they need to avoid for huge app projects while keeping the rest.

**Comment by ocha** [comment]
@ryan-roemer I dont think "folks are surprised that minification causes a CPU hit". Folks are surprised that there is minification and zippin of whole app happening on every file update in DEV ENV. usually folks expect unminified package with comments and full source when developing and dont expect any optimizations and minification while developing... 

I agree with having opting-out of minification while keeping rest of `inspectpack` analyses. That would be best of both worlds.

**Comment by ryan-roemer** [comment]
Hi @ocha , @lukastong , @FourwingsY and anyone else watching this one!:

I've added a PR / branch at https://github.com/FormidableLabs/webpack-dashboard/pull/230 that I'd love folks to kick the tires on. Inspectpack flags `minified` and `gzip` are exposed, the docs are updated, and I've even added an explanation about the inspectpack cache daemon too.

Let us know how it goes!
