### ISSUE TITLE
version 2 does not resize on terminal resize

### ISSUE THREAD

**Issue by mschaaf** [FormidableLabs/webpack-dashboard#251]
> Please provide a description of the bug / issue, and provide the details below:

====================================================================

###### If the issue is visual, please provide screenshots here
![bildschirmfoto vom 2018-05-29 22-45-00](https://user-images.githubusercontent.com/703355/40684631-1d8ce1d0-6392-11e8-801f-a56b627e5d63.png)

====================================================================

###### Steps to reproduce the problem
1. start in a terminal, e.g. with the following terminals gnome-terminal, st
2. resize window, smaller or wider
3. webpack-dashboard stays at its initial size
====================================================================

###### Please provide a gist of relevant files

1. `webpack-dashboard -- ./node_modules/.bin/webpack-dev-server --mode=development --config webpack.dev.js --hot`
2. webpack config:
```
const merge = require('webpack-merge');
const common = require('./webpack.common.js');
var DashboardPlugin = require('webpack-dashboard/plugin');
var path = require('path');

const config = merge(common, {
  mode: 'development',
  output: {
    filename: path.join('js', '[name].dev.js'),
    publicPath: 'http://localhost:8080/'
  },
  optimization: {
    // for dashboard plugin
    minimize: false
  },
  plugins: [
    new DashboardPlugin()
  ],
  devtool: 'eval',
  devServer: {
    contentBase: path.resolve(__dirname, 'dist'),
    port: 8080,
    compress: false,
    hot: true,
    inline: true,
    historyApiFallback: true,
    progress: true,
    stats: {
      children: false,
      modules: true,
      cached: true,
      colors: true,
      chunk: true
    }
  }
})

module.exports = config;

```

====================================================================

###### More Details

- What operating system are you on? Ubuntu Linux 18.04
- What terminal application are you using? different st, gnome-terminal, alacritty and tmux inside of these terminals
- What version of webpack-dashboard are you using? 2.0.0
- What is the output of running `echo $TERM`? with tmux: tmux-256color without tmux: xterm-256color

**Comment by pixelass** [comment]
This package is one of the reasons why I don't contribute to certain repos.

Who ever made this made is an explorer. 
Who ever uses this is a fool.

This is just an IMHO

I don't develop on repos using this plugin simply because it messes with my workflow. 
It's a nice idea which has a horrible implementation and gotten too much hype.

Whatever happened to the idea of low-dependency stacks?


Just my humble opinion. 
There are too many tools that fix one thing and break N other things along the way.
We argue about those issues instead of developing the app we initially planned.

Thank you

**Comment by ryan-roemer** [comment]
@pixelass -- We've put a lot of sweat, tears and ❤️ into this project (including a from-scratch rewrite of it's internal engine to make it super fast and not CPU hogging as it was in previous versions). Console-based programs (using `blessed`) tend to have a lot of kinks in general, but we use `blessed` rather than try to re-implement all that wonky stuff ourselves.

And we're in "mostly" good shape with the current state of the project, but are still trying to keep up with our most breaking issues / bugs across all our supported projects in this org. 

And any project you're working in you can pretty easily temporarily/permanently disable the plugin if it's really mucking with your workflow :( 

But if a terminal resize bug on Linux is tweaking your workflow, I'm presuming you're on Linux, and if you (or anyone else with access to an Ubuntu desktop)  _did_ find the time, we'd ❤️ someone to dive in, play around, and see if they could give us any hints or tips on the potential root issue / fixes!

**Comment by mschaaf** [comment]
This issue seems to be fixed with the latest 3.x version. I cannot reproduce it any longer. Maybe the move to neo-blessed fixed it or my patience to wait or ... ;-)
