### ISSUE TITLE
gzip size

### ISSUE THREAD

**Issue by jdalton** [FormidableLabs/webpack-dashboard#29]
I'm usually concerned more with the gzip size ([gzip-size](https://www.npmjs.com/package/gzip-size)/[pretty-bytes](https://www.npmjs.com/package/pretty-bytes)).
It would be nice if the report offered that.

**Comment by kenwheeler** [comment]
On it.

**Comment by ryan-roemer** [comment]
@kenwheeler -- Might want to make this "opt in" if this adds sync / compile time that will be noticeable to users in their build times, etc.

**Comment by chrisblossom** [comment]
Although the idea of using gzip size is great, it is not very practical in development because it will not represent the size of the production build. For example, I show lodash taking up 22.9% of the total size, yet in production I don't even have lodash in my build (I think redux-dev-tools is bringing it in, not sure though). React and many other modules are a lot smaller when in production as well. Just something to be aware of.

**Comment by ryan-roemer** [comment]
@kenwheeler -- Do we still need this or do we already have this in latest versions?
