### ISSUE TITLE
About mutliple webpack config

### ISSUE THREAD

**Issue by Kmaschta** [FormidableLabs/webpack-dashboard#36]
Hi, great work with webpack-dashboard!

Assume we have a `webpack.config.babel.js` as:

``` js
export default [
    require('webpack/first.config.babel.js'),
    require('webpack/second.config.babel.js'),
];
```

Files `first.config.babel.js` and `second.config.babel.js` are webpack configs.

How am I supposed to configure webpack-dashboard?
Should I add the plugin to both files ? If I do this, it seems to be pretty buggy.

**Comment by kenwheeler** [comment]
hmm. thats a tough one. what are the two configs? is there one that you are interested in vs the other?

**Comment by Kmaschta** [comment]
Nope, it's two part of the same application and I really want the data of twice apps. (But both are simple webpack config)

What about this?
```js
var config = require('./webpack.config.babel'); // The same file as above with two apps
var webpack = require('webpack');
var WebpackDevServer = require('webpack-dev-server');

var compiler = webpack(config);
var server = new WebpackDevServer(compiler, {
    // Install dashboard like in the README
});

server.listen(8080);
```

**Comment by kenwheeler** [comment]
Does that work for you?

**Comment by kenwheeler** [comment]
You might have to write your own handler function that merges the outputs and then calls setData on the dashboard.

**Comment by Kmaschta** [comment]
I'll try this later and let you know! Thanks

**Comment by GGAlanSmithee** [comment]
I'm hijacking this issue for a bit, as I have a similar question (tell me if you prefer me to make a separate issue).

I have a setup which is based on the one [here]
(https://github.com/reactGo/reactGo/tree/master/webpack).

From [package.json](https://github.com/reactGo/reactGo/blob/master/package.json#L14) two script are run via `npm run dev`: [`build:dev`](https://github.com/reactGo/reactGo/blob/master/package.json#L15), which builds (and watches) the server, and [`babel-node`](https://github.com/reactGo/reactGo/blob/master/package.json#L9), which runs the app with HMR.

There are two different webpack config files for these scripts: [`dev-server`](https://github.com/reactGo/reactGo/blob/master/webpack/webpack.config.dev-server.js) and [`dev-client`](https://github.com/reactGo/reactGo/blob/master/webpack/webpack.config.dev-client.js) respectively. I have succesfully added `webpack-dashboard` to each of these scripts / config files, but the problem is this:

If I `npm run build:dev` using `webpack-dashboard`, I cannot see the client (HMR) output.
If I `npm run dev` using `webpack-dashboard`, I will see HMR output, but if there's an error in the server code (which is watched by `nodemon`) it will output the error in the same console, which breaks `webpack-dashboard`

What I would like to do is to run two npm scripts (one watching the server build using `nodemon` and another one running the server with HMR) and have both their output in `webpack-dashboard`, is this possible?

Thanks in advance @kenwheeler et al!

_Something like this (psuedo code):_
```javascript
nodemon --exec webpack-dashboard -- webpack --config webpack.config.dev-server.js && webpack-dashboard -- babel-node server/index.js`

**Comment by ryan-roemer** [comment]
Chiming in here -- webpack currently allows (1) a config object (what we're all familiar with) and/or (2) an **array** of config objects. 

@kenwheeler -- Perhaps we should consider some means of detection of other webpack configs from the same originating process id (aka the node webpack you're running at root on the multiple configs).

**Comment by ryan-roemer** [comment]
`webpack-dashboard@^2` should handle any webpack config using normal "add a plugin" means.
