### ISSUE TITLE
Sometimes nothing displayed on dashboard

### ISSUE THREAD

**Issue by ningt** [FormidableLabs/webpack-dashboard#72]
Sometimes nothing displayed on dashboard, does anyone have the same issue?

<img width="801" alt="screen shot 2016-08-19 at 9 25 13 am" src="https://cloud.githubusercontent.com/assets/5404896/17793971/ddcc43a8-65ee-11e6-8f35-836c313c160c.png">

**Comment by dmarkow** [comment]
I spent some time digging into this today. It turned out to be an issue with the way `json-sockets` sends/receives multi-byte characters.

The dashboard's webpack plugin sends a `done` message, which includes a `stats` object that has a ton of info about the build in it.  The message is then stringified (in my case, it was an 8mb string) and sent over a socket to the `webpack-dashboard` process.

However, the receiving socket receives the message in chunks; sometimes the split point between two chunks happens to be the middle of a multi-byte character. `json-sockets` tries to convert the first byte of the multi-byte character to a string and fails, falling back to a � character. It then receives the second byte of the character in the next chunk and also converts it to a �. So now the string is longer than it's supposed to, so the last character is ignored (supposed to be a `]`), causing `JSON.parse` to fail.

I made a pull request on the library (See https://github.com/sebastianseilund/node-json-socket/pull/25) but the library's been inactive for over a year so I'm not optimistic.

I happened to "fix" this by removing a ton of multibyte characters from my project -- the main culprit was all of the locale files from moment.js -- setting my webpack config to only include the English locale got rid of the problem for me (and helped shrink my build by 300k too).

An easier way would probably be to follow the "webpack-dev-server (the old way)" instructions in the README (which bypasses the separate webpack-dashboard executable and use of sockets).

**Comment by exogen** [comment]
Wow, nice detective work @dmarkow. Seems like it would be wise for us to switch to a more robust socket library. It's probably an easy fix (don't convert from Buffer → String until the full message is received?) but if it's inactive that'll be tough...

**Comment by dmarkow** [comment]
@exogen The fix was similar -- using StringDecoder to handle the Buffer to String conversion (which automatically holds any incomplete character parts until it receives the rest).

**Comment by jing2si** [comment]
windows 10
@dmarkow how to fix this problem

**Comment by jing2si** [comment]
> I happened to "fix" this by removing a ton of multibyte characters from my project -- the main culprit was all of the locale files from moment.js -- setting my webpack config to only include the English locale got rid of the problem for me (and helped shrink my build by 300k too).

@dmarkow how to do this?

**Comment by kenwheeler** [comment]
@dmarkow @exogen are there any recommended alternatives? I'd be willing to fork if not.

**Comment by kenwheeler** [comment]
Merged and released fix in 0.1.5
