### ISSUE TITLE
Running webpack without dashboard with plugin active

### ISSUE THREAD

**Issue by Valkertok** [FormidableLabs/webpack-dashboard#75]
Webpack returns an error when trying to use it without webpack-dashboard binary with plugin active
![webpackerr](https://cloud.githubusercontent.com/assets/8319728/17802229/52a9ce20-65ef-11e6-8d6d-b798b9663bc7.png)

Is the any way to use webpack alone (e.g. for CI friendly output) without this error, or somehow detect in webpack.config.js if webpack-dashboard binary is used?

**Comment by kenwheeler** [comment]
What does your dashboard plugin constructor look like?

**Comment by Valkertok** [comment]
in webpack.config.js
```
var DashboardPlugin = require('webpack-dashboard/plugin');

config = {
  ...

  plugins: [
    ...,
    new DashboardPlugin(),
    ...
  ]
}
```

then if I use `webpack` instead of `webpack-dashboard -- webpack` it returns this error

**Comment by kenwheeler** [comment]
hmmm. I'll have to add an option. Right now it assumes if no handler is provided, that we are using sockets.

**Comment by kenwheeler** [comment]
Turns out, this is sort of tough to get done easily, from an API standpoint. My personal recommendation would be to create a webpack.config.dashboard.js and just extend your webpack dev config to include the dashboard plugin. You probably shouldn't/don't want the dashboard plugin overhead in in your regular webpack build anyway.
