### ISSUE TITLE
Customizable dashboard

### ISSUE THREAD

**Issue by burakcan** [FormidableLabs/webpack-dashboard#9]
Hello and thank you for this great idea 💯 
Do you plan to improve this to support custom layouts etc?
Maybe you can optionally let user to specify blessed options as a quick fix.

**Comment by kenwheeler** [comment]
Totally. The original version (before I open sourced it) had react render stats and a mirror of the web console. The problem was, it was sort of hacked together. Subsequent versions will include the ability to provide custom panes, and some recipes and helpers for front end socket connections and express middleware for request logging.

**Comment by burakcan** [comment]
Thanks 🎉  that way, we can implement redux-devtools-webpack then :)
